name: release

on:
  push:
    tags: ["4.*"]

jobs:
  main:
    uses: ./.github/workflows/main.yml
  docker:
    needs: main
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build, tag and push Docker multi-arch manifest to Docker Hub
        run: |
          docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
          docker buildx create --use
          VERSION="$(cat VERSION)"
          echo "Docker tag is: ${VERSION}"
          docker buildx build --platform linux/amd64,linux/arm64,linux/arm/v7 --tag adferrand/backuppc:${VERSION} --tag adferrand/backuppc:4 --tag adferrand/backuppc --push .
  github:
    needs: docker
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install python
        uses: actions/setup-python@v4
        with:
          python-version: 3.8
      - name: Get version and changelog
        id: get-version
        run: |
          VERSION="$(cat VERSION)"
          echo "Version is: ${VERSION}"
          echo "VERSION=${VERSION}" >> "${GITHUB_OUTPUT}"
          python utils/extract_changelog.py "${VERSION}" > extracted_changelog.md
      - name: Create GitHub release
        uses: softprops/action-gh-release@v1
        with:
          name: Docker BackupPC ${{ steps.get-version.outputs.VERSION }}
          body_path: extracted_changelog.md
